### ISSUE TITLE
Search existing SPN by AppId does not yield results

### ISSUE THREAD

**Issue by dasabate** [MicrosoftDocs/customer-insights#28]
On paragraph _Look for an existing service principal - Step 4_ searching for the AppId (0bfc4568-a4ba-4c58-bd3e-5d3e76bd7fff) doesn't produce any results, even when the Service Principal is already registered. Think the text could be replaced by the Object Id (was "8ecfc703-7ddd-4f43-af7c-c9ada88c6866" in my case but not sure if this is universal) or by searching with the App name. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 447e1566-ce81-f273-f049-8c53fa84f65f
* Version Independent ID: 447e1566-ce81-f273-f049-8c53fa84f65f
* Content: [Connect to an Azure Data Lake Storage account by using a service principal - Dynamics 365 Customer Insights](https://docs.microsoft.com/en-us/dynamics365/customer-insights/connect-service-principal?source=docs)
* Content Source: [ci-docs/connect-service-principal.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/connect-service-principal.md)
* Service: **customer-insights**
* Sub-service: **audience-insights**
* GitHub Login: @adkuppa
* Microsoft Alias: **adkuppa**

**Comment by m-hartmann** [comment]
@dasabate thank you for reaching out. We've looked into this and turns out, you have to add a filter for the app ID. Simply searching the appID in the search field won't yield results. The object ID is dynamic so you'd have to either use the search field to look up the name or add the filter "Application ID starts with" for 0bfc4568-a4ba-4c58-bd3e-5d3e76bd7fff.

I've updated the documentation to clarify this in step 4. 

I'll close this issue and invite you to reopen it or create a new one if you need further information. 

Thanks, 
Michael
